### ISSUE TITLE
FeathersJS Service Methods Support:

### ISSUE THREAD

**Issue by oberoivarun** [rollymaduk/feathers-neo4j-driver#2]
I was trying out the library and it works well. Great going. Looking into the code i found that you only have the 'create' method available.

Though i can run any cypher query i want through that function, feathers emits 'created' events for all uses.

I tried to modify it a little, but went into errors that were beyond my scope. Something to do with the express router middleware.

I understand that there are only certain keyword methods that have registered middleware. Going deeper i found that methods array inside the Router module has all the keywords that can be used. I tried adding a custom keyword ('find'), but it gave the middleware error. After that i could not understand the code any further. 

Could you provide some guidance. I'm a newbie to express/ feathersJS.

**Comment by rollymaduk** [comment]
Hi @oberoivarun,  please what version of the library are you using as the most recent version consists of several other custom methods such as `queryTransaction()`,`commitTransaction()` and `rollbackTransaction()`, kindly share your custom method implemention and your stacktrace

**Comment by oberoivarun** [comment]
I am using the latest version. And i have used the other methods.

But my concern is that using any of those methods will not trigger any of the default events, like 'created' and 'updated'. Hence, methods with those names will need to be used. 

As far as custom implementation, i only changed the key name 'create'  to 'get'. As i found that it is one of the node methods allowed.

Is there any way i could use the existing methods and still get all the feathers events?

**Comment by rollymaduk** [comment]
No! custom methods are not handled by feathers events but, a work around can be to use [eventfilters](https://docs.feathersjs.com/real-time/filtering.html)  or [after hooks](https://docs.feathersjs.com/hooks/usage.html) to alter/customize responses. As for the errror received implementing standard service methods, make sure your method parameters and return values are correct for the method. example of standard service class with method signatures below 
```js 
class MyService {
  find(params [, callback]) {}
  get(id, params [, callback]) {}
  create(data, params [, callback]) {}
  update(id, data, params [, callback]) {}
  patch(id, data, params [, callback]) {}
  remove(id, params [, callback]) {}
  setup(app, path) {}
}
```
If I could see a copy of your stacktrace error, I might be able to provide you more concrete help.

**Comment by oberoivarun** [comment]
I only need the REST methods supported by feathersjs. But i can't figure out how to use them. I have only so far gotten to 'create'. The other methods you mentioned in your service class, i cannot reach.

Here's what i have gotten so far:

`
feathers generate service -> service_name -> db -> neDb -> no to authentication
`

Then i make these changes:

```

'use strict';

const path = require('path');
// const NeDB = require('nedb'); //Comment this
// const service = require('feathers-nedb'); //Comment this
const service = require('feathers-neo4j-driver'); //Add this
const hooks = require('./hooks');

module.exports = function(){
  const app = this;


//Comment all of this
  // const db = new NeDB({
  //   filename: path.join(app.get('nedb'), 'tasks.db'),
  //   autoload: true
  // });

  let options = {
    // Model: db, //Comment this
    //Add these options
      uri:'http://localhost:7474',
      user:"varun",
      pass:"varun",
    paginate: {
      default: 5,
      max: 25
    }
  };

  // Initialize our service with any options it requires
  app.use('/tasks', service(options));

  // Get our initialize service to that we can bind hooks
  const taskService = app.service('/tasks');

  // Set up our before hooks
  taskService.before(hooks.before);

  // Set up our after hooks
  taskService.after(hooks.after);
};
```

In my client side app, i do this:

`
this.service._app.create({query:'CREATE (n:TASK {key:{value}});',params:{value:"My first Task"}});
`

This works. But now if i do any other method, like find or remove etc. There is no return as the method do not exist.

`
this.service._app.find
`

How do i add these methods?

**Comment by oberoivarun** [comment]
This is where i am stuck. I'm sorry if the solution is really basic. I'm just new to node.

I'm using angular 2 for the front end, neo4j 3.1 and feathers 2.0.3.

I create a new service using the feathers-cli and then alter it like this:

```
'use strict';

const path = require('path');
const service = require('feathers-neo4j-driver');
// const NeDB = require('nedb');
// const service = require('feathers-nedb');
const hooks = require('./hooks');

module.exports = function(){
  const app = this;

  // const db = new NeDB({
  //   filename: path.join(app.get('nedb'), 'tasks.db'),
  //   autoload: true
  // });

  let options = {
    uri: "http://localhost:7474",
    user: "neo4j",
    pass: "neo4j",
    // Model: db,
    paginate: {
      default: 5,
      max: 25
    }
  };

  // Initialize our service with any options it requires
  app.use('/tasks', service(options));

  // Get our initialize service to that we can bind hooks
  const taskService = app.service('/tasks');

  // Set up our before hooks
  taskService.before(hooks.before);

  // Set up our after hooks
  taskService.after(hooks.after);
};

```

Then, through my client app i send a request through websocket like this:

`    // this.service._app.create({query:'CREATE (n:TASK {key:{value}});',params:{value:"My first Task"}}).then(res => console.log(res.data)).catch(err => console.error(err));
`

This works. No problems.

But if i do this:
`
this.service._app.find({query:'MATCH (n:TASK) return n;'});
`

It doesn't work. It just times out. 

How do i get all the methods that you mentioned above to work?

**Comment by rollymaduk** [comment]
Hi, indeed it is an expected behavior because the feathers-neo4j-driver does not implement a find() method, there are 2 ways to deal with this.

1.  Fork the feathers-neo4j-driver and extend its class methods to include a find() method. You will find an instance of node-neo4j object for implementing CYPHER within its methods.

OR

2. Use the feathers-cli to generate 2 generic services e.g(neo4jService, taskService), instantiate feathers-neo4j plugin in the first, and wrap it within the second class, using an instance of the plugin to implement CYPHER queries for your specific methods i.e (find(),get(),create(),remove(),patch())

**EXAMPLE**

```js
/* neo4jService.js*/
'use strict';

const path = require('path');
const service = require('feathers-neo4j-driver');
// const NeDB = require('nedb');
// const service = require('feathers-nedb');
const hooks = require('./hooks');

module.exports = function(){
  const app = this;
  let options = {
    uri: "http://localhost:7474",
    user: "neo4j",
    pass: "neo4j"
  };

  // Initialize our service with any options it requires
  app.use('/neo4j', service(options));
};
```
```js
/* taskService.js*/

'use strict';

const hooks = require('./hooks');

class Service {
  
  setup(app){
//instantiate neo4j plugin here
  this.neo4j=app.service('neo4j')
}
 
  find(params) {
    return this.neo4j.create({query:'MATCH (n:TASK) return n;'})
  }

  get(id, params) {
    return this.neo4j.create({query:'//YOUR CYPHER QUERY '})
  }

  create(data, params) {
    return this.neo4j.create({query:'CREATE (n:TASK {key:{value}});',params:{value:params.value}})
                .then(res=>res)

  }

  update(id, data, params) {
    return this.neo4j.create(/*neo4j args here!*/)
  }

  patch(id, data, params) {
    return this.neo4j.create(/*neo4j args here!*/)
  }

  remove(id, params) {
    return this.neo4j.create(/*neo4j args here!*/)
  }
}

module.exports = function(){
  const app = this;

  // Initialize our service with any options it requires
  app.use('/tasks', new Service());

  // Get our initialize service to that we can bind hooks
  const taskService = app.service('/tasks');

  // Set up our before hooks
  taskService.before(hooks.before);

  // Set up our after hooks
  taskService.after(hooks.after);
};

module.exports.Service = Service;

```

then in your client call your taskService with the implemented methods!.

**Comment by oberoivarun** [comment]
Hey! Thanks a ton. I had written the wrapper class and had just gotten it working. But your second option is easier. Thanks again.

I'll be using this a lot, so when i have a more efficient class, i can send it to you. If you like it, you can add it to the repo.
