### ISSUE TITLE
Tutorial is unclear on how to get started.

### ISSUE THREAD

**Issue by fedevela** [rollymaduk/feathers-neo4j-driver#3]
hello @rollymaduk i am trying to follow the example tutorial where it says I should call 

```
const plugin = require('feathers-neo4j-driver');
const app = feathers();
const options={uri:'http://localhost:7474',user:"neo4j",pass:"root"};
app.use('/neo4j', plugin(options));
```

However i get the following error: `throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))`

Any help is highly appreciated!!! Thanks in advance!

**Comment by rollymaduk** [comment]
@fedevela what version of express are you using?

**Comment by rollymaduk** [comment]
@fedevela please kindly share your working code, perhaps a sample repo so that I can try to reproduce the error. thanks. It sounds like the problem is from your express server setup

**Comment by fedevela** [comment]
@rollymaduk thank you for your reply, I am sorry I dropped this. We are again at the stage where we will be prototyping feathers-neo4j-driver to determine its viability in our project.

It is our first choice. Thank you very much for your work!!!!

Best regards.
